seed: 007
log_level: "INFO"
log_format: "%(asctime)s - %(levelname)s - %(message)s"
###########  Data storing: folders and filenames 
data_storage:
  local_data_path: "data"
  input_file_names: ['SamplePopulation_Albertsons_CandyBeverages_Compiled','SamplePopulation_Albertsons_HealthBeauty_Compiled']
  intermediate_file_name: 'processed' #TODO: change it back to main 
  output_file_names: '_output_results'
  processed_main_file_names: '_processed_input_data'
  processed_targets_file_names: '_targets'
  processed_split_file_names: ['_train','_validation','_test']
  input_extension: "/*.csv"
  save_extension: ".csv"
  features_file_name: "_processed_features"
  target_file_name: "_processed_target"
  binarized_file_name: "_processed_binarized"
  target_col_input: "Category Code"
  target_extension: ".csv"
###########  Preprocessing the train test split and validation don't go beyond 1 
execution:
  local_execution_path: "execution_files"
  target_col_binarizer_name: "target_col_binarizer"
  pickle_extension: ".pkl"
###########  Preprocessing the train test split and validation don't go beyond 1 
preprocessing:
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
###########  Data storing: folders and filenames 
model:
  feature_cols: ["Category","Product Description", "Size"]
  feature_name: "feature"
  target_col_list: "target_list"
  target_input_name: "Category Description"
  target_col_name: "target"
  target_col_binarized: "target_binarized"
  learning_rate: 0.01
  hidden_dim: 5
  num_workers: 10
  max_epochs: 1
  decision_metric: "test_mcc"
  max_len: 500
  batch_size: 50

